config/routes.rb
Doctors::Application.routes.draw do

  get "site/about"
  get "site/home"

  match '/users/index' => 'users#index'
  match '/about'=> 'site#about'
  match '/home' => 'site#home'
  match '/search' => 'users#search'
  match '/users/index_doctor' => 'users#index_doctor'
  match '/users/index_patient' => 'users#index_patient'
  match '/appointment/:id' => 'user#new'
  match '/specialisation/:id' => 'doctors#specialisation'

  resources :users  do
    resources :doctors
    resources :patients
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :specialisations
  resources :sessions
  resources :appointments
  resources :doctors
  resources :patients
  resources :hours

  root :to => 'site#about'

end

app/models/patient.rb
class Patient < User
  attr_accessible :hour, :hour_ids, :hour_id, :specialisation_id, :specialisation_ids, :appointments, :appointments_id, :appointment_id, :doctor, :hour

  has_many :appointments
  accepts_nested_attributes_for :appointments

  has_secure_password
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_filter :is_admin?, :only => [:index, :destroy]
  skip_filter :authorize, :only => [:new, :create]
    def index
      @patients = Patient.all
     # @appointments = Appointment.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @patients }
        end
    end

  def show
    if current_user
      if !current_user.admin
        @patient = Patient.find(current_user.id)
      else
        @patient = Patient.find(params[:id])
      end
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @patient }
    end
  end

  def new
      @patient = Patient.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @patient }
      end
    end

    def edit
      @patient = Patient.find(params[:id])
     #@appointments = Appointment.all
    end

    def create
      @patient = Patient.new(params[:patient])

      respond_to do |format|
        if @patient.save
          format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
          format.json { render json: @patient, status: :created, location: @patient }
        else
          format.html { render action: "new" }
          format.json { render json: @patient.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      patients = Patient.find(params[:id])
      @patient = Patient.find(params[:id])

      respond_to do |format|
        if @patient.update_attributes(params[:patient])
          format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @patient.errors, status: :unprocessable_entity }
        end
      end
    end


    def destroy
      @patient = Patient.find(params[:id])
      @patient.destroy

      respond_to do |format|
        format.html { redirect_to patients_url }
        format.json { head :no_content }
      end
    end

end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
    <% if @patient.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

          <ul>
            <% @patient.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :dob %><br />
      <%= f.date_select :dob, :start_year => Time.now.year - 90, :end_year => Time.now.year - 16 %>
    </div>
    <div class="field">
      <%= f.label :pps_no %><br />
      <%= f.text_field :pps_no %>
    </div>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.text_field :password %>
    </div>
    <div class="field">
      <%= f.label :gender %><br />
      <%= f.select :gender, Patient::GENDERS, prompt: 'Select your gender' %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/patients/edit.html.erb
<% "Edit Patient" %>

<%= form_for @patient, :url => patient_path do |f| %>
    <%= render 'form' %>
<% end %>

app/views/patients/index.html.erb
<div>
  <% if notice %>
      <p class="notification notice">
        <%= notice %>
      </p>
  <% end %>

  <% if alert %>
      <p class="notification alert">
        <%= alert %>
      </p>
  <%end%>
<h1>List of all patients</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Dob</th>
    <th>Pps no</th>
    <th>Email</th>
    <th>Gender</th>
    <th colspan="3">Action</th>
  </tr>

  <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.first_name %></td>
        <td><%= patient.last_name %></td>
        <td><%= patient.dob %></td>
        <td><%= patient.pps_no %></td>
        <td><%= patient.email %></td>
        <td><%= patient.gender %></td>


        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Patient', new_patient_path %>

</div>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>
<div id="text-content">

  <p>
    <b>First name:</b>
    <%= @patient.first_name %>
  </p>

  <p>
    <b>Last name:</b>
    <%= @patient.last_name %>
  </p>

  <p>
    <b>Dob:</b>
    <%= @patient.dob %>
  </p>

  <p>
    <b>Pps no:</b>
    <%= @patient.pps_no %>
  </p>

  <p>
    <b>Email:</b>
    <%= @patient.email %>
  </p>

  <p>
    <b>Gender:</b>
    <%= @patient.gender %>
  </p>

  <%= link_to 'Edit', edit_patient_path(@patient) %> |
  <%= link_to 'Back', patients_path %>
</div>