config/routes.rb
Doctors::Application.routes.draw do

  get "site/about"
  get "site/home"

  match '/users/index' => 'users#index'
  match '/about'=> 'site#about'
  match '/home' => 'site#home'
  match '/search' => 'users#search'
  match '/users/index_doctor' => 'users#index_doctor'
  match '/users/index_patient' => 'users#index_patient'
  match '/appointment/:id' => 'user#new'
  match '/specialisation/:id' => 'doctors#specialisation'

  resources :users  do
    resources :doctors
    resources :patients
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :specialisations
  resources :sessions
  resources :appointments
  resources :doctors
  resources :patients
  resources :hours

  root :to => 'site#about'

end

app/models/doctor.rb
class Doctor < User
  attr_accessible :hour, :hour_ids, :hour_id, :specialisation_id, :specialisation_ids
  has_many :hours
  accepts_nested_attributes_for :hours

  has_secure_password
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_filter :authorize, :except => [:index]
  skip_filter :is_admin?, :only => [:index]

  #def specialisation
   # @doctors = Doctor.find_all_by_specialisation(params[:id])
    #@specialisation = params[:id]
       #respond_to do |format|
     # format.html # index.html.erb
      #format.json {render json:@doctors}
   # end
  #end



    def index
      @doctors = Doctor.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @doctors }
      end
    end

    def show
      if current_user
        if !current_user.admin
        @doctor = Doctor.find(current_user.id)
       # @appointments = current_user.appointments.all
        else
          @doctor = Doctor.find(params[:id])
        end
        @specialisations = Specialisation.all



      else
        @doctor = Doctor.find(params[:id])
        #@appointments = @doctor.appointments.all
      end
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @doctor }
      end
    end

    def new
      @doctor = Doctor.new
      @specialisations = Specialisation.all

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @doctor }
      end
    end

    def edit
      @doctor = Doctor.find(params[:id])
      @specialisations = Specialisation.all
     # @appointments = Appointment.all
    end

    def create
      @doctor = Doctor.new(params[:doctor])

      respond_to do |format|
        if @doctor.save
          format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
          format.json { render json: @doctor, status: :created, location: @doctor }
        else
          format.html { render action: "new" }
          format.json { render json: @doctor.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      @doctor = Doctor.find(params[:id])

      respond_to do |format|
        if @doctor.update_attributes(params[:doctor])
          format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @doctor.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @doctor = Doctor.find(params[:id])
      @doctor.destroy

      respond_to do |format|
        format.html { redirect_to doctors_url }
        format.json { head :no_content }
      end
    end

end

app/helpers/doctor_helper.rb
module DoctorHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
    <% if @doctor.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

          <ul>
            <% @doctor.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :dob %><br />
      <%= f.date_select :dob, :start_year => Time.now.year - 90, :end_year => Time.now.year - 16 %>
    </div>
    <div class="field">
      <%= f.label :pps_no %><br />
      <%= f.text_field :pps_no %>
    </div>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.text_field :password %>
    </div>
    <div class="field">
      <%= f.label :gender %><br />
      <%= f.select :gender, Doctor::GENDERS, prompt: 'Select your gender' %>
    </div>


    <div class="specialisation">
      <% @specialisations.each do |specialisation| %>
          <p>
            <%= check_box_tag "doctor[specialisation_ids][]", specialisation.id, @doctor.specialisations.include?(specialisation) %>
            <%= specialisation.name %>
          </p>
      <% end %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/doctors/edit.html.erb
<% "Edit Doctor" %>

<%= form_for @doctor, :url => doctor_path do |f| %>
    <%= render 'form' %>
<% end %>

app/views/doctors/index.html.erb
<h1>List of all doctors</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <% if current_user %>
        <% if current_user.admin %>
            <th>Dob</th>
            <th>Pps no</th>
        <% end %>
    <% end %>
    <th>Email</th>
    <th>Gender</th>
    <th>Specialization</th>
    <% if current_user %>
        <% if current_user.admin %>
            <th colspan="3">Action</th>
        <% end %>
    <% end %>
  </tr>

  <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.first_name %></td>
        <td><%= doctor.last_name %></td>
        <% if current_user %>
            <% if current_user.admin %>
                <td><%= doctor.dob %></td>
                <td><%= doctor.pps_no %></td>
            <% end %>
        <% end %>
        <td><%= doctor.email %></td>
        <td><%= doctor.gender %></td>
        <td><%= doctor.specialisations.map(&:name).join(", ") %></td>
        <% if current_user %>
            <% if current_user.admin %>
                <td><%= link_to 'Show', doctor %></td>
                <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
                <td><%= link_to 'Destroy', doctor, method: :delete, data: {confirm: 'Are you sure?'} %></td>
            <% end %>
        <% end %>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New doctor</h1>

<%= render 'form' %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>
<div id="text-content">

  <p><b>First name:</b><%= @doctor.first_name %></p>
  <p><b>Last name:</b><%= @doctor.last_name %></p>
  <p><b>Dob:</b><%= @doctor.dob %></p>
  <p><b>Pps no:</b><%= @doctor.pps_no %></p>
  <p><b>Email:</b><%= @doctor.email %></p>
  <p><b>Gender:</b><%= @doctor.gender %></p>
  <p>
    <b>Specialisation:</b>
    <%= @doctor.specialisations.map(&:name).join(", ") %>
  </p>

  <%= link_to 'Edit', edit_doctor_path(@doctor) %> |
  <%= link_to 'Back', doctors_path %>
</div>

app/views/doctors/x_doctorDistinctList.html.erb
<%@doctors = Doctor.select('DISTINCT specialisation')%>

<% @doctors.each do |c| %>
    <a href="/specialisation/<%=c.specialisation%>" id="specialisationlisting"><%=c.specialisation%></a>
    <br/>
<%end%>