config/routes.rb
Doctors::Application.routes.draw do

  get "site/about"
  get "site/home"

  match '/users/index' => 'users#index'
  match '/about'=> 'site#about'
  match '/home' => 'site#home'
  match '/search' => 'users#search'
  match '/users/index_doctor' => 'users#index_doctor'
  match '/users/index_patient' => 'users#index_patient'
  match '/appointment/:id' => 'user#new'
  match '/specialisation/:id' => 'doctors#specialisation'

  resources :users  do
    resources :doctors
    resources :patients
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :specialisations
  resources :sessions
  resources :appointments
  resources :doctors
  resources :patients
  resources :hours

  root :to => 'site#about'

end

app/models/ability.rb
class Ability
  include CanCan::Ability
end

def initialize(user)
  user ||= User.new # guest user
  can :manage, :all
  if user.role? :Admin
    can :manage, :all
   # can :create, :Appointment
    can :create, :Specialisation
    can :create, :User
  elsif user.role? :Doctor
    can :read, [Appointment, Specialisation]
    can [:edit, :update], Appointment
  elsif user.role? :Patient
    can :manage, :Appointment;  Appointment.try(:user) == user
    can :edit, :User; User.try(:user) == user

  end
  end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  attr_accessible  :user_id, :users_ids, :doctors_id, :hour_id, :doctor_id, :patient, :patient_id, :id

  belongs_to :patient
  has_one :hour
end

app/models/doctor.rb
class Doctor < User
  attr_accessible :hour, :hour_ids, :hour_id, :specialisation_id, :specialisation_ids
  has_many :hours
  accepts_nested_attributes_for :hours

  has_secure_password
end

app/models/hour.rb
class Hour < ActiveRecord::Base
  attr_accessible :appointment_date, :appointment_time, :doctor_id, :appointment_id, :id
  belongs_to :appointment
  belongs_to :doctor
  accepts_nested_attributes_for :appointment
  end

app/models/patient.rb
class Patient < User
  attr_accessible :hour, :hour_ids, :hour_id, :specialisation_id, :specialisation_ids, :appointments, :appointments_id, :appointment_id, :doctor, :hour

  has_many :appointments
  accepts_nested_attributes_for :appointments

  has_secure_password
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users, :through => :roles_users
  has_many :roles_users
  #Roles = %w[admin, doctor, patient]
  attr_accessible :id, :name
end

app/models/roles_user.rb
class RolesUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
  end

app/models/specialisation.rb
class Specialisation < ActiveRecord::Base
  attr_accessible :description, :name, :user_id, :users, :doctor_id
 has_and_belongs_to_many :users
  #accepts_nested_attributes_for :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

  validates :pps_no,
            presence: true
  validates :first_name,
            :length =>{:minimum => 2, :maximum => 50}
  validates :last_name,
            :length =>{:minimum => 2, :maximum => 50}
  validates :gender,
            presence: true
  validates :dob,
            presence: true


  validates :email, presence: true, uniqueness: true
  validates :password,
            :length => {:minimum => 8, :maximum => 16, :on => :create}
  validates :email,
            :length => {:minimum => 5, :maximum => 50},
            :format => {:with =>
                            /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i}
  before_create { generate_token(:auth_token) }
  #before_create :setup_role

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :dob, :first_name, :last_name, :gender, :pps_no, :specialisation, :specialisation_id, :specialisation_name, :roles, :roles_id, :roles_name, :appointments, :appointments_id, :patient, :doctor_id, :specialisation_ids
  # attr_accessible :title, :body

  #has_many :appointments, :through => :users_appointments
  #has_many :users_appointments
  #belongs_to :appointment


  has_and_belongs_to_many :specialisations

  has_many :roles, :through => :roles_users
  has_many :roles_users
  has_secure_password
  GENDERS = [ "Female", "Male" ]
#Roles = %w[admin, doctor, patient]
  def role?(role)
    return !!self.roles.find_by_name(role.to_s)
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

end

app/controllers/hours_controller.rb
class HoursController < ApplicationController
  before_filter :authorize, :except => [:index]
  skip_filter :is_admin?, :only => [:index]

  # GET /hours
  # GET /hours.json
  def index
    @hours = Hour.all
    @doctors = Doctor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hours }
    end
  end

  # GET /hours/1
  # GET /hours/1.json
  def show
    @hour = Hour.find(params[:id])
    @doctors = Doctor.all


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hour }
    end
  end

  # GET /hours/new
  # GET /hours/new.json
  def new
    @hour = Hour.new
    @doctors = Doctor.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hour }
    end
  end

  # GET /hours/1/edit
  def edit
    @hour = Hour.find(params[:id])
    @doctors = Doctor.all
  end

  # POST /hours
  # POST /hours.json
  def create
    @hour = Hour.new(params[:hour])

    respond_to do |format|
      if @hour.save
        format.html { redirect_to @hour, notice: 'Hour was successfully created.' }
        format.json { render json: @hour, status: :created, location: @hour }
      else
        format.html { render action: "new" }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hours/1
  # PUT /hours/1.json
  def update
    @hour = Hour.find(params[:id])

    respond_to do |format|
      if @hour.update_attributes(params[:hour])
        format.html { redirect_to @hour, notice: 'Hour was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hours/1
  # DELETE /hours/1.json
  def destroy
    @hour = Hour.find(params[:id])
    @hour.destroy

    respond_to do |format|
      format.html { redirect_to hours_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def about
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/doctor_helper.rb
module DoctorHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/hours_helper.rb
module HoursHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
                    <!DOCTYPE html>
                    <html xmlns="http://www.w3.org/1999/html">
                    <head>
                      <title>Doctors</title>
                      <%= stylesheet_link_tag "application", :media => "all" %>
                      <%= javascript_include_tag "application" %>
                      <%= csrf_meta_tags %>
                      <!--added 11.03.2013 with gem devise-->
                      <p class="notice"><%= notice %></p>

                      <p class="alert"><%= alert %></p>

                    </head>
                    <body>
                    <div id="container">
                      <div id="top_box">
                        <div id="links">
                          <!-- REF. login devise 2.1.3 RailsCast -->
                          <% if current_user %>
                              Logged in as <strong><%= current_user.email %></strong>
                              <%= link_to 'Logout', logout_path, :method => :delete %>
                          <% else %>
                              <%= link_to "Sign up", new_patient_path %> |
                              <%= link_to "Login", login_path %>
                          <% end %>
                          <!--should not be here->  <!-- REF. END -->
                        </div>
                      </div>
                      <div id="bottom_box">
                        <%= image_tag("viola.jpg", :id => "bg") %>
                        <!--Photography by: Monika Rosik-->
                        <div id="total">
                          <div id="banner">
                            <%= image_tag("logo2.png", :size => '400x130') %>
                          </div>
                          <div id="menu">
                            <ul id="navigation">
                              <li><a href="about.html">About</a></li>
                              <li><a href="/doctors">Doctors</a></li>
                              <% if current_user %>
                                  <% if current_user.admin %>
                                      <li><a href="/patients">Patients</a></li>
                                  <% end %>
                              <% end %>
                              <li><a href="/specialisations">Specialisations</a></li>
                              <li><a href="/appointments/new">Book Appointment</a></li>
                              <li><a href="/home">Information</a></li>
                            </ul>
                          </div>

                          <!--<ul id="specialisationlisting">
                             <!--'//*#< = render 'doctors/x_doctorDistinctList' %>
                           </ul>    -->

                          <div id="column">
                            <div id="side">
                              <% if current_user %>
                                  <br/>
                                  <%= link_to 'New Appointment', new_appointment_path %>
                                  <br/>
                                  <%= link_to 'Doctors Appointments', hours_path %>
                                  <br/>
                                  <% if current_user.admin %>
                                      <%= link_to 'All Users', users_path, :class => "#{'selected' if @tab=='users'}" %>
                                      <br/>
                                      <%= link_to 'New Patient', new_patient_path %>
                                      <br/>
                                      <%= link_to 'New Doctor', new_doctor_path %>
                                      <br/>
                                      <%= link_to 'New Specialisation', new_specialisation_path %>
                                      <br/>
                                      <%= link_to 'New Time Slot for Appointment', new_hour_path %>
                                      <br/>
                                      <%= link_to 'Appointments List', appointments_path %>
                                      <br/>
                                  <% end %>
                              <% end %>
                            </div>

                            <div id="main">
                              <%= yield %>
                            </div>
                          </div>

                          <div id="footer">
                            <p>Online Doctors © All rights reserved </p>
                          </div>
                        </div>

                    </html>